# Generated by Django 5.0.7 on 2024-07-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification_preference',
            field=models.IntegerField(choices=[(1, '1 day before'), (2, '2 days before'), (3, '3 days before'), (4, '4 days before'), (4, '4 days before'), (5, '5 days before'), (6, '6 days before'), (7, '7 days before')], default=1),
        ),
    ]
